### ISSUE TITLE
doesn't evaluate equations using \frac, output is ⚡

### ISSUE THREAD

**Issue by Sikeen** [Developer-Mike/calctex#10]
`$\frac {56,941 915 6}{356,199 465 4}  \times 100 == ⚡$`
![Screenshot_20240426_095928](https://github.com/Developer-Mike/calctex/assets/92328005/e4e9921b-c1d8-4de9-b83e-cd45493db2cc)

`$56.941 915 6 / 356.199 465 4  \times  100 == \frac{28.470.957.800}{1.780.997.327}$`
![Screenshot_20240426_095736](https://github.com/Developer-Mike/calctex/assets/92328005/0c7b3bc5-9e0f-4d6a-9b1f-413f6fc6637a)

multiplication command set as `\times`

Execute set as "=="

**Comment by Developer-Mike** [comment]
It is caused by #9

**Comment by Sikeen** [comment]
🤦
