### ISSUE TITLE
Feature Request: Keyboard Shortcut to Insert Result

### ISSUE THREAD

**Issue by eiiot** [Developer-Mike/calctex#5]
I mainly use Vim in Obsidian, so clicking on the equation to insert it into my LaTeX code isn't ideal. Would it be possible to add some sort of GitHub Copilot-style autocomplete, where the user can press tab (or some other key preferably) to insert the result of the calculation?

**Comment by Developer-Mike** [comment]
This function has been added in the latest version. You cannot currently select the key, but it will be added eventually.
