### ISSUE TITLE
Feature Request: Evaluate fractions into decimal

### ISSUE THREAD

**Issue by AdamFipke** [Developer-Mike/calctex#7]
First I just wanna say this plugin is absolutely amazing! Super lightweight, and exactly the workflow I wanted. 

One feature request I have is to have the option for fractions to be evaluated into decimal, which I think would be more useful for physics or chemistry calculations. Example:

Doing `1770/135 =` with the plugin right now would give `118/9`. Instead, I think it could be cool to have the option for it to give `13.1`

Maybe it could also have the option of choosing the number of significant figures. Another option is to have numbers greater than 100 or less than 0.01, for example, would be put in scientific notation)

**Comment by Developer-Mike** [comment]
This is definitely a planned feature. But ATM I have other stuff to do...

**Comment by Developer-Mike** [comment]
Just closing this issue because #11 summarizes everything.
