### ISSUE TITLE
Feature Request: options to change the multiply operator and group separator

### ISSUE THREAD

**Issue by AdamFipke** [Developer-Mike/calctex#8]
Personally, I like my times operators to show up as `\times` (which will get rendered as an `x`). Also, having the option to make the group separator a space `" "` or blank `""` would be very nice.

**Comment by Developer-Mike** [comment]
Can you please explain what you mean with the "group separator"?

**Comment by Developer-Mike** [comment]
This was added in version `1.3.3` 👍🏻
